import {
  Award,
  Bell,
  BookOpen,
  Building2,
  CalendarDays,
  Check,
  ChevronRight,
  ClipboardCheck,
  Code2,
  Compass,
  Cpu,
  Database,
  Download,
  ExternalLink,
  FileText,
  Globe,
  GraduationCap,
  Grid2x2,
  Handshake,
  Heart,
  Image,
  Info,
  Landmark,
  Layers,
  LibraryBig,
  Link2,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Monitor,
  Newspaper,
  Palette,
  Phone,
  Presentation,
  Printer,
  QrCode,
  Radio,
  Rocket,
  ScrollText,
  Send,
  Server,
  Share2,
  ShieldCheck,
  Sparkles,
  Star,
  Tv,
  User,
  Users,
  Wrench,
} from "lucide-react";

export const iconRegistry = {
  award: Award,
  bell: Bell,
  book: BookOpen,
  building: Building2,
  calendar: CalendarDays,
  check: Check,
  chevronRight: ChevronRight,
  clipboard: ClipboardCheck,
  code: Code2,
  compass: Compass,
  cpu: Cpu,
  database: Database,
  download: Download,
  external: ExternalLink,
  file: FileText,
  globe: Globe,
  graduationCap: GraduationCap,
  grid: Grid2x2,
  handshake: Handshake,
  heart: Heart,
  image: Image,
  info: Info,
  landmark: Landmark,
  layers: Layers,
  library: LibraryBig,
  link: Link2,
  mail: Mail,
  mapPin: MapPin,
  megaphone: Megaphone,
  message: MessageCircle,
  monitor: Monitor,
  newspaper: Newspaper,
  palette: Palette,
  phone: Phone,
  presentation: Presentation,
  printer: Printer,
  qrCode: QrCode,
  radio: Radio,
  rocket: Rocket,
  scroll: ScrollText,
  send: Send,
  server: Server,
  share: Share2,
  shield: ShieldCheck,
  sparkle: Sparkles,
  star: Star,
  tv: Tv,
  user: User,
  users: Users,
  wrench: Wrench,
} as const;

export type IconName = keyof typeof iconRegistry;
